### ISSUE TITLE
Provide a kirbytag that allows users to embed responsive images

### ISSUE THREAD

**Issue by dweidner** [dweidner/kirby-responsive-image#1]
Implement a custom kirbytag that uses the implemented file methods (see https://getkirby.com/docs/developer-guide/kirbytext/tags)

**Comment by tristantbg** [comment]
Made a kirbytag out of [resizeOnDemand](https://github.com/SebastianEberlein/kirby-resize-on-demand-plugin) while waiting yours :
https://github.com/tristantbg/J3r3mV/blob/master/site/tags/image.php
