### ISSUE TITLE
Usage in template

### ISSUE THREAD

**Issue by tristantbg** [dweidner/kirby-responsive-image#2]
Can you please explain in the Readme how to use it in templates ?

I've been waiting for a plugin like this since a longtime.
I am using this one : https://github.com/SebastianEberlein/kirby-resize-on-demand-plugin
But it is not very clean to use in templates.

Thanks

**Comment by dweidner** [comment]
Sure, I will add a new section to the README once I am back home. Basically this plugin provides new file methods that allow you to generate responsive images using the `srcset` attribute. In your template you should be able to add `echo $page->image()->responsiveImageTag()` to your template. You can customize your layout breakpoints via plugin options or a files meta information. Similar to the way it is implemented in WordPress.

**Comment by tristantbg** [comment]
Great, thank you. I have read the source code but was not sure how it worked ;)

**Comment by dweidner** [comment]
Let me know if something is missing.
